name: pyRevitCI
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
      # under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: snickerbockers/submodules-init@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          pip install pipenv
          pipenv install

      - name: Check build environment
        run: pipenv run pyrevit check

      - name: Build Binaries
        run: |
          pipenv run pyrevit set year
          pipenv run pyrevit set build
          pipenv run pyrevit set products
          pipenv run pyrevit build all

      - name: Get Build Version
        id: buildversion
        uses: juliangruber/read-file-action@v1
        with:
          path: pyrevitlib/pyrevit/version

      - name: Sign Binaries
        uses: skymatic/code-sign-action@v1
        with:
          certificate: "${{ secrets.CERTIFICATE }}"
          password: "${{ secrets.PASSWORD }}"
          certificatesha1: "${{ secrets.CERTIFICATESHA1 }}"
          certificatename: "${{ secrets.CERTIFICATENAME }}"
          description: "pyRevit"
          timestampUrl: "http://timestamp.digicert.com"
          folder: "bin"
          recursive: true

      - name: Build Installers
        run: |
          pipenv run pyrevit build installers

      - name: Sign Installers
        uses: skymatic/code-sign-action@v1
        with:
          certificate: "${{ secrets.CERTIFICATE }}"
          password: "${{ secrets.PASSWORD }}"
          certificatesha1: "${{ secrets.CERTIFICATESHA1 }}"
          certificatename: "${{ secrets.CERTIFICATENAME }}"
          description: "pyRevit"
          timestampUrl: "http://timestamp.digicert.com"
          folder: "dist"
          recursive: true

      # default retention period is 90 days
      # https://github.com/marketplace/actions/upload-a-build-artifact#retention-period
      - name: Upload Installers
        uses: actions/upload-artifact@v2
        with:
          name: pyrevit-installers
          path: |
            dist/pyRevit_${{ steps.buildversion.outputs.content }}_signed.exe
            dist/pyRevit_${{ steps.buildversion.outputs.content }}_admin_signed.exe
            dist/pyRevit_CLI_${{ steps.buildversion.outputs.content }}_signed.exe
            dist/pyRevit_CLI_${{ steps.buildversion.outputs.content }}_admin_signed.exe
