name: pyRevitCI
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      # under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          pip install pipenv
          pipenv install

      - name: Check build environment
        run: pipenv run pyrevit check
